### ISSUE TITLE
For preventing idling heroku app

### ISSUE THREAD

**Issue by kuznetsov-m** [PiyushDixit96/binance-spot-order-notification-heroku#5]
Signing up for the UptimeRobot service and further setup can seem daunting.
There is an easier way - **Heroku Scheduler**.
1. Add add-on Heroku Scheduler
2. Create task `curl "http://{app_name}.herokuapp.com"`
3. Chose interval 10 min

**Comment by PiyushDixit96** [comment]
Thanks. I will add it to my repo.

**Comment by PiyushDixit96** [comment]
Solved. Thanks
